Section "ServerLayout"
	Identifier     "X.org Configured"
	Screen      0  "Screen0" 0 0
EndSection

Section "Files"
	ModulePath   "/usr/lib/xorg/modules"
	FontPath     "built-ins"
EndSection

Section "Device"
	Identifier  "Card0"
	Driver      "rdcm15"
	BusID       "PCI:0:13:0"
EndSection

Section "Monitor"
	Identifier   "Monitor0"
	VendorName   "Monitor Vendor"
	ModelName    "Monitor Model"
	HorizSync    30-90
	VertRefresh  50-60
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
	DefaultDepth 24
	SubSection "Display"
		Viewport   0 0
		Depth     24
		Modes    "1920x1200" "1920x1080" "1680x1050" "1600x1200" "1440x900" "1280x1024" "1366x768" "1280x720" "1024x768" "800x600" "640x480"
	EndSubSection
EndSection
