Section "ServerLayout"
	Identifier     "X.org Configured"
	Screen      0  "Screen0" 0 0
EndSection

Section "Files"
	ModulePath   "/usr/lib/xorg/modules"
	FontPath     "built-ins"
EndSection

Section "Device"
	Identifier  "Card0"
	Driver      "rdcm15"
	BusID       "PCI:0:13:0"
EndSection

Section "Monitor"
	Identifier   "Monitor0"
	VendorName   "Monitor Vendor"
	ModelName    "Monitor Model"
EndSection

Section "Screen"
	Identifier "Screen0"
	Device     "Card0"
	Monitor    "Monitor0"
	DefaultDepth 24
	SubSection "Display"
		Viewport   0 0
		Depth     24
		Modes "1024x768" "800x600"
	EndSubSection
EndSection
